services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    environment:
      - COLLECTOR_ZIPKIN_HTTP_HTTP_PORT=9411
      - LOG_LEVEL=debug
    ports:
      - "5775:5775/udp"     # Jaeger Agent (compact protocol)
      - "6831:6831/udp"     # Jaeger Agent (thrift compact)
      - "6832:6832/udp"     # Jaeger Agent (thrift binary)
      - "5778:5778"         # Jaeger Agent config API
      - "16686:16686"       # Jaeger Web UI
      - "14268:14268"       # Jaeger Collector HTTP endpoint (spans)
      - "14250:14250"       # Jaeger Collector gRPC endpoint
      - "9411:9411"         # Zipkin-compatible endpoint
    networks:
      - jaeger-example


#http://localhost:16686

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    ports:
      - "4317:4317"   # OTLP gRPC receiver
      - "55680:55680" # OpenTelemetry metrics HTTP receiver
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    command: [
      "--config", "/etc/otel-collector-config.yaml"
    ]
    networks:
      - jaeger-example
networks:
  jaeger-example:
    driver: bridge